// Assignment Code provided
var generateBtn = document.querySelector("#generate");

// Function used to generate a random password
/*This function prompts for lowercase, uppercase, special, and numeric characters*/
function createPassword() {
  var lowercaseChars = "abcdefghijklmnopqrstuvwxyz";
  var uppercaseChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  var specialChars = "!@#$%^&*()";
  var numericChars = "0123456789";

  var password = "";

  var passwordLength = prompt("Enter password length (between 8 and 128):");
  passwordLength = parseInt(passwordLength);

  if (isNaN(passwordLength) || passwordLength < 8 || passwordLength > 128) {
    alert("Please enter a valid password length between 8 and 128.");
    return "";
  }

  var useLowercase = confirm("Include lowercase characters?");
  var useUppercase = confirm("Include uppercase characters?");
  var useSpecialChars = confirm("Include special characters?");
  var useNumericChars = confirm("Include numeric characters?");

  var allowedChars = "";

  if (useLowercase) {
    allowedChars += lowercaseChars;
  }

  if (useUppercase) {
    allowedChars += uppercaseChars;
  }

  if (useSpecialChars) {
    allowedChars += specialChars;
  }

  if (useNumericChars) {
    allowedChars += numericChars;
  }

  if (allowedChars === "") {
    alert("You must select at least one character type.");
    return "";
  }

  for (var i = 0; i < passwordLength; i++) {
    var randomNumber = Math.floor(Math.random() * allowedChars.length);
    password += allowedChars.substring(randomNumber, randomNumber + 1);
  }

  return password;
}

// Function to write password to the password variable
/*This writes the password generated by the above function into our box*/
function writePassword() {
  var password = createPassword();
  if (password !== "") {
    var passwordText = document.querySelector("#password");
    passwordText.value = password;
  }
}

// Event listener added to generate a random passward when the "generate" button is clicked
/*This waits to generate our password until the "Generate" button is clicked by the user*/
generateBtn.addEventListener("click", writePassword);

